# Generated by Django 4.2.6 on 2023-11-13 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(default='street', max_length=30)),
                ('room_type', models.CharField(max_length=10)),
                ('mini_kitchenette', models.BooleanField()),
                ('private_bathroom', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_name', models.CharField(default='room-1.jpg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.dormroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
